import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AD eCommerce",
  description: "Generated by AmethystDesign",
  icons: {
    icon: "/AD-logo.gif",
  },
  openGraph: {
    title: "AD eCommerce",
    description: "Generated by AmethystDesign",
    url: "https://ad-ecommerce.vercel.app/",
    siteName: "AD eCommerce",
    images: [
      {
        url: "https://ad-ecommerce.vercel.app/AD-logo.gif",
        width: 1200,
        height: 630,
      },
    ],
  },  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <head>
        Next.js will add it automatically both locally and after deploying to Vercel.
        <link rel="icon" type="image/gif" href={(metadata.icons as { icon: string }).icon} />
      </head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-full flex-col bg-white dark:bg-gray-950 dark:text-white dark:antialiased text-gray-900`}
      >
        <Navbar />
        <main className="flex-grow container mx-auto px-4 py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
